import type { Database } from "../types/database.types";

const database: Database = {
  posts: [
    {
      id: 1,
      title: "His mother had always taught him",
      body: "His mother had always taught him not to ever think of himself as better than others. He tried to live by this motto, but a difficult conversation challenged that belief.",
      tags: ["history", "american", "crime"],
      reactions: { likes: 192, dislikes: 25 },
      views: 305,
      userId: 121,
    },
    {
      id: 2,
      title: "He was an expert but not in a discipline",
      body: "He had mastered the small art of making perfect soft-serve cones. It was not a famous skill, but it took years of patience and repetition.",
      tags: ["french", "fiction", "english"],
      reactions: { likes: 859, dislikes: 32 },
      views: 4884,
      userId: 91,
    },
    {
      id: 3,
      title: "The archive opened after midnight",
      body: "The researcher found a missing catalog card behind the cabinet. It pointed to a sealed box no one had requested in thirty years.",
      tags: ["mystery", "archive", "research"],
      reactions: { likes: 341, dislikes: 18 },
      views: 1290,
      userId: 74,
    },
    {
      id: 4,
      title: "A small city changed its traffic lights",
      body: "The council expected complaints after the new timing system launched. Instead, drivers noticed shorter waits and fewer crowded intersections.",
      tags: ["urban", "planning", "technology"],
      reactions: { likes: 512, dislikes: 44 },
      views: 2307,
      userId: 188,
    },
  ],

  events: [
    {
      id: 1,
      title: "Riverside Jazz Night",
      description:
        "A free open-air concert featuring three local quartets. Bring a blanket; food trucks arrive at sunset.",
      category: "music",
      location: { venue: "Riverside Park", city: "Portland", country: "USA" },
      startDate: "2026-07-12T18:00:00Z",
      endDate: "2026-07-12T22:30:00Z",
      capacity: 800,
      attendees: 643,
      tags: ["music", "outdoor", "community"],
      organizerId: 121,
      status: "upcoming",
    },
    {
      id: 2,
      title: "Open Source Maintainers Summit",
      description:
        "A one-day gathering for project maintainers to swap burnout survival tactics and governance models.",
      category: "technology",
      location: {
        venue: "Hall C, Convention Center",
        city: "Berlin",
        country: "Germany",
      },
      startDate: "2026-09-03T09:00:00Z",
      endDate: "2026-09-03T17:00:00Z",
      capacity: 250,
      attendees: 250,
      tags: ["technology", "conference", "developers"],
      organizerId: 91,
      status: "sold_out",
    },
    {
      id: 3,
      title: "Coastal Cleanup Morning",
      description:
        "Volunteers meet at the north pier to collect debris before the tide turns. Gloves and bags provided.",
      category: "volunteering",
      location: { venue: "North Pier", city: "Brighton", country: "UK" },
      startDate: "2026-05-30T07:30:00Z",
      endDate: "2026-05-30T11:00:00Z",
      capacity: 120,
      attendees: 88,
      tags: ["environment", "volunteering", "outdoor"],
      organizerId: 74,
      status: "completed",
    },
    {
      id: 4,
      title: "Late Night Pasta Workshop",
      description:
        "A hands-on class where each guest rolls, cuts, and plates their own fresh tagliatelle.",
      category: "food",
      location: { venue: "Cucina Lab", city: "Bologna", country: "Italy" },
      startDate: "2026-06-21T20:00:00Z",
      endDate: "2026-06-21T23:00:00Z",
      capacity: 16,
      attendees: 14,
      tags: ["food", "workshop", "cooking"],
      organizerId: 188,
      status: "upcoming",
    },
  ],

  tasks: [
    {
      id: 1,
      title: "Migrate user table to new schema",
      description:
        "Add the verified_at column and backfill existing rows in batches to avoid locking the table.",
      status: "in_progress",
      priority: "high",
      dueDate: "2026-06-10T17:00:00Z",
      createdAt: "2026-05-28T10:15:00Z",
      assigneeId: 91,
      tags: ["backend", "database", "migration"],
      completed: false,
      progress: 60,
    },
    {
      id: 2,
      title: "Write onboarding email sequence",
      description:
        "Draft five emails covering setup, first win, tips, social proof, and a check-in.",
      status: "todo",
      priority: "medium",
      dueDate: "2026-06-18T12:00:00Z",
      createdAt: "2026-05-30T08:00:00Z",
      assigneeId: 121,
      tags: ["marketing", "copywriting", "email"],
      completed: false,
      progress: 0,
    },
    {
      id: 3,
      title: "Fix flaky checkout test",
      description:
        "The payment integration test fails intermittently under load. Reproduce, isolate the race condition, and stabilize.",
      status: "in_progress",
      priority: "urgent",
      dueDate: "2026-06-05T15:00:00Z",
      createdAt: "2026-06-01T09:45:00Z",
      assigneeId: 74,
      tags: ["testing", "ci", "bug"],
      completed: false,
      progress: 35,
    },
    {
      id: 4,
      title: "Archive Q1 financial reports",
      description:
        "Export the closed quarterly statements to cold storage and update the index spreadsheet.",
      status: "done",
      priority: "low",
      dueDate: "2026-05-20T17:00:00Z",
      createdAt: "2026-05-12T11:30:00Z",
      assigneeId: 188,
      tags: ["finance", "admin", "archive"],
      completed: true,
      progress: 100,
    },
  ],
};

export default database;
